nimbus_ip: 172.16.241.133

nimbus_login:
  text_field:
    username: admin
    password: admin

wizard_network:
  text_field:
    address: 172.16.241.133
    netmask: 255.255.255.0
    gateway: 172.16.241.1
    dns1: 172.16.241.1
    dns2: 8.8.8.8
