before_wizard_ip: 192.168.17.129
after_wizard_ip: 192.168.17.133

email_notif:
  checkbox:
    active: true
    tls_support: true
  tex_field:
    send_to: lucasmcastro@gmail.com
    email_host: smtp.gmail.com
    email_port:  25
    email_user: nimbus.backup.test@gmail.com
    email_password: LseXtvIByjYT8UHRECjMSw0BM

wizard_network:
  text_field:
    address: 192.168.17.133
    netmask: 255.255.255.0
    gateway: 192.168.17.1
    dns1: 192.168.17.1
    dns2: 8.8.8.8

login_credentials:
  text_field:
    username: admin
    password: admin

wrong_login_credentials:
  text_field:
    username: silly
    password: wrong

wizard_timezone:
  text_field:
    ntp_server: a.ntp.br
  select_list:
    country: Brazil
    area: America/Recife

wizard_password:
  text_field:
    new_password1: admin
    new_password2: admin

edit_client1:
  text_field:
    name: Client 1
    description: This machine was added by watir automated test.

edit_timezone:
  select_list:
    country: Argentina
    area: America/Argentina/Buenos_Aires

undo_edit_timezone:
  select_list:
    country: Brazil
    area: America/Recife
